name: armadillo_tests

on: push 

jobs:
  cpp-helloworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docker images
        run: sudo apt-get update
      - name: compile hello world
        run: |
          cd HelloWorld && g++ -o HelloWorld && ./HelloWorld
