name: armadillo_tests

on: push 

jobs:
  cpp-helloworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docker images
        run: |
          apt-get update && apt-get install -y \
          git build-essential cmake	libopenblas-dev \
        	liblapack-dev libarpack2 libarmadillo-dev
      - name: compile hello world
        run: |
          cd HelloWorld && g++ -o HelloWorld && ./HelloWorld
