name: cpp_docker_tests

on: push 

jobs:
  cpp-helloworld:
    runs-on: ubuntu-latest
    container: mtmiller/octave
    steps:
      - uses: actions/checkout@v3
      - name: Build docker images
        run: docker build -t local < Dockerfile
      - name: Run tests
        run: docker run -it -v $PWD:/srv -w/srv local echo "hola"
      - run: cd HelloWorld && ./HelloWorld
