name: docker_octave_tests

on: push 

jobs:
  docker_tests:
    runs-on: ubuntu-latest
    container: gnuoctave/octave:latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd test
          octave --eval "test_local"
