# This is a basic workflow to help you get started with Actions
name: moxunit_master_test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  matlab-codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: matlab-actions/setup-matlab@v0
      - uses: matlab-actions/run-tests@v0
        with:
          source-folder: tests/src tests/srcB
          code-coverage-cobertura: coverage.xml
      - uses: codecov/codecov-action@v1
        with:
          file: coverage.xml

