# This is a basic workflow to help you get started with Actions
name: moxunit_testCoverage

# Controls when the action will run.
on: [push, pull_request]

jobs:
  coverage_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joergbrech/moxunit-action@v1.3.0
        with:
          src: .
          tests: test/moxunit_testWithCoverage.m
          with_coverage: true
          cover_xml_file: coverage.xml
      - uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
